BLACK_VALUE = 1
RED_VALUE = -1
DRAW_VALUE = 0
NUM_OF_BEASTS = 4
VERBOSE = True
animal_cnt = [0 for i in range(NUM_OF_BEASTS)]
POSSIBLE_PLAYER_VALUES = [BLACK_VALUE, RED_VALUE]
WASP_WEIGHT_COL_CONST = 'wasp weight'
CHAM_WEIGHT_COL_CONST = 'chameleon weight'
SNAKE_WEIGHT_COL_CONST = 'snake weight'
CHEET_WEIGHT_COL_CONST = 'cheetah  weight'
BLACK_PERC_COL_CONST = 'black win percentages'
RED_PERC_COL_CONST = 'red win percentages'
DRAW_PERC_COL_CONST = 'draw percentages'
RED_BLACK_DIFF_COL_CONST = 'abs(red% - black%)'
DRAW_WEIGHT_COL = 'draw weight'
DRAW_MAX_WEIGHT_COL = 'draw max weight'
DRAW_DIFF_FROM_GOLDEN_COL = "abs(draw% - golden draw%)"
